apiVersion: v1
kind: Secret
metadata:
  name: ms-auth-jwt-keys
  namespace: ms-auth
type: Opaque
stringData:
  private_key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmsrbBtnxcBMGt
    31uvJhj71gTKi3jT2eOF8Hg6NQvc3LO1TUofN7QORkYEw5TD4GZiS8WCS2lUd5Dd
    e6d3jQ0J3k1Oke4O27Ml2s1bgS07ljC/iV3EUWKfLgpwrbz+Erao/avRLtubJaLy
    QAvZI9FrHARQFK5Ut449p97ks90IhtnLQ6qK/H7cxpf0JSd40WnlpLIENiF2wpkT
    2DDAPDMsXWHgdxdAsOBndvsTVADiBGaiyoIaTqNVNN+vcxIKDOZT48ZAwN2AlBxZ
    7xGX9zwlFa/a9xEJDLDz7VQyJe9tWdr/i/r/sHWy3TNl5AsDhywJvzhnUrRbJB+M
    orO7dY2TAgMBAAECggEAEDqxAU4PcHQEGTX4OqamYwpUoBWRF2sMtDMTuXMFqySP
    mHSkZUKqlIMx+O/DsYhM34AKBCPsZs1XPMD3rnN8k/vhIeeiOi8Yk3RobuK2MSlv
    qI4qo1zbEa1NVegMUN4oi25bBnwd5E53PUeP/711e4yYPOWujU/rmMQZtsFuIRC7
    hcncKzk4yHxtFRVdyl6Kbe4zP0y+Af9K1yfxR80VTlIhNocyZhawdHS/IH5OPRdp
    8q4qAVgYtJw3x+3FpeThGmLTftFr3LkFk+rcguLCHG3orhRc9qj45+T48i/pbT+O
    yyDbSiKDn2eYW5CImXcXR6tuQpYeT6EAJSrd2iq9VQKBgQDjWIWtmMGn5OSQb8C2
    VyoQrb6i4FEtP/UwRDkLC94w29Z/EQX0VUw9H3TB65xWkxTL2lALu/XjlF32ZMVT
    E23u8GwaBIXOASruQ2ffm/0sQ4T81Si+igWF7SkwnCYfDm9bPENilhNhzygRj6hL
    /Gtj19yJvj/5N4Pg0d0TaJrxzQKBgQC7tVmLMj/Qilc+Z20X499JeLYBcD9WSIY9
    M0EAwyM+5ysgAq6Bndp0fi+JuyY7nX08DPuMWu6kzYqQIlqMpLXWDm5jpfnqMsMP
    1piCx9O+0584G8+vRykMdWh8c0d3u/rtbfUk9gyglNap8fZUAHDKjTcfUrHhSRZv
    Jn/u4bSc3wKBgAx2yPVof4193g4RImacxsCdVetGEw1BCWc5BkuVvfu9wbe7rjDk
    EEb1l4geK7cPXz+B24uZJXTxqGkewza3xPopkjOm9dMCe2EOrv4yZiHsHbli0lYH
    6R+bjfuNRAXF29MLrcIU6kEdg1vbHWX1E8oohn3CwW0fXwqPVuh+fqgtAoGBAJ7x
    kt8hL5QgcHuxDFl8ZShLhKJ3L8qaIsFT0ykYE5JCIOw8GRQ8XCzkZNCVnmxAkTj2
    LVLN9OGsAjbGQDJzjl2xXpwWgSZk0XNp3T5wgsZFX78dHaFn+kRIbq9i1hN3I6VE
    xJ4Fku+u2I6TCmha7yc0qIZneaQwRUTdLttSV6O1AoGAZuPYa6ol/CI+IkII+4PR
    NQy+gQfpnjsV0oCLoY4ZrETEa5j5KLCbCZpeX+lxtT413uFf1nFIfx1kbAXlJeP3
    R+7hpwzmo1WkAaSLaSpfyg8vU5OsaqglzscWK9M5zRfe9I31JhHKgvibUpZblCN3
    XhhaBjfMf7XUYmQ1L2YVYT0=
    -----END PRIVATE KEY-----
  public_key.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAprK2wbZ8XATBrd9bryYY
    +9YEyot409njhfB4OjUL3NyztU1KHze0DkZGBMOUw+BmYkvFgktpVHeQ3Xund40N
    Cd5NTpHuDtuzJdrNW4EtO5Ywv4ldxFFiny4KcK28/hK2qP2r0S7bmyWi8kAL2SPR
    axwEUBSuVLeOPafe5LPdCIbZy0Oqivx+3MaX9CUneNFp5aSyBDYhdsKZE9gwwDwz
    LF1h4HcXQLDgZ3b7E1QA4gRmosqCGk6jVTTfr3MSCgzmU+PGQMDdgJQcWe8Rl/c8
    JRWv2vcRCQyw8+1UMiXvbVna/4v6/7B1st0zZeQLA4csCb84Z1K0WyQfjKKzu3WN
    kwIDAQAB
    -----END PUBLIC KEY-----
